### ISSUE TITLE
Add pCloud support

### ISSUE THREAD

**Issue by tobihagemann** [cryptomator/cloud-access-swift#3]
Depends on https://github.com/pCloud/pcloud-sdk-swift/issues/8

Edit: SPM support has been added upstream. 🚀

**Comment by aryus96** [comment]
Would be great to have this feature !

**Comment by aryus96** [comment]
If it can help in order to be reused, the feature seems to be already deployed on Android App ?

https://github.com/cryptomator/android/pull/283

**Comment by tobihagemann** [comment]
We are obviously aware of that. 😅 And there are most definitely lessons learned that can be transferred to iOS.

We haven't created a roadmap for 2022 yet but adding support for pCloud (and S3) are very high on the list. If someone else in the community beat us at it, so be it. pCloud integration on Android was actually an open-source contribution.

**Comment by aamck** [comment]
+1 for S3 support for iOS. That would really unlock Cryptomator for my mobile workflow.

**Comment by tobihagemann** [comment]
@aamck That would be a different feature request. Just opened one: #7
