### ISSUE TITLE
Using the Dropbox SDK from a forked repository instead of the original one.

### ISSUE THREAD

**Issue by phil1995** [cryptomator/cloud-access-swift#5]
https://github.com/cryptomator/ios/blob/705a05a01a603c4314de61b54780525dd6837846/CloudAccessPrivate/Package.swift#L27

Because of conflicts when used with Cocoapods and Swift Package Manager, we need to integrate the Dropbox Obj-C SDK with Swift Package Manager. Officially there is no Swift Package Manager support for the SDK yet. Once the PR has been accepted, we should use the official repository as a dependency again.

**Comment by tobihagemann** [comment]
> The team has decided not to support Swift Package Manager for the Dropbox Objective-C SDK. While you're free to fork and modify it under [the MIT license](https://github.com/dropbox/dropbox-sdk-obj-c/blob/master/LICENSE), there currently are not plans to add and support this feature officially. Apologies I don't have better news!

🤷‍♂️
